version: '3'

services:

    app:
        build: .
        container_name: java-service-dev
        tty: true
        networks:
            - java-service-dev-network
        ports:
            - 8080:8080 

networks:
    java-service-dev-network:
        driver: bridge